server:
  port: 9010

spring:
  application:
    name: goods
  redis:
    host: localhost
    port: 6379
    jedis:
       pool:
         maxActive: 3
         maxIdle: 3
         minIdle: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goods?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: admin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    publisher-returns: true

eureka:
   instance:
     prefer-ip-address: true
   client:
     service-url:
       defaultZone:  http://127.0.0.1:9200/eureka/



