server:
  port: 9010

spring:
  application:
    name: goods
  redis:
    host: localhost
    port: 6379
    jedis:
       pool:
         maxActive: 3
         maxIdle: 3
         minIdle: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goods?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
  rabbitmq:
    host: 220.249.111.162
    port: 16777
    username: admin
    password: adminrabbitmq123
    publisher-confirms: true
    publisher-returns: true

eureka:
   instance:
     prefer-ip-address: true
   client:
     service-url:
       defaultZone:  http://127.0.0.1:9200/eureka/

# 定时任务
xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      address: ''
      appname: goods
      ip: ''
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9999

rocketmq:
  consumer:
    consumeMessageBatchMaxSize: 1
    consumeThreadMax: 32
    consumeThreadMin: 5
    groupName: ${spring.application.name}
    isOnOff: 'on'
    namesrvAddr: 127.0.0.1:9876
    topics: TopicTest~TestTag;TestTopic~HelloTag;HelloTopic~HelloTag;MyTopic~*




