server:
  port: 9210
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: true    #关闭服务器自我保护，客户端心跳检测15分钟内错误达到80%服务会保护，导致别人还认为是好用的服务
    eviction-interval-timer-in-ms: 15000 #清理间隔（单位毫秒，默认是60*1000）
  client:
    register-with-eureka: true #是否将自己注册到eureka中
    fetch-registry: true #是否从eureka中获取信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:9200/eureka/
spring:
  application:
    name: eureka
