server:
  port: 9201

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone:  http://127.0.0.1:9200/eureka/


spring:
  application:
    name: gateway
  redis:
    host: localhost
    port: 6379
    jedis:
       pool:
          maxActive: 3
          maxIdle: 3
          minIdle: 0
  cloud:
    gateway:
         globalcors:
           cors‐configurations:
            '[/**]': # 匹配所有请求
             allowedOrigins: "*" #跨域处理 允许所有的域
             allowedMethods: # 支持的方法
             - GET
             - POST
             - PUT
             - DELETE
         discovery:
               locator:
                 enabled: true
         routes:
         - id: oauth
           uri: lb://oauth
           predicates:
           - Path=/oauth/**
           filters:
           - StripPrefix=1
         - id: goods
           uri: lb://goods
           predicates:
           - Path=/goods/**
           filters:
           - StripPrefix=1
           - name: RequestRateLimiter
             args:
              key-resolver: '#{@ipKeyResolver}'
              redis-rate-limiter.replenishRate: 100
              redis-rate-limiter.burstCapacity: 300

