server:
  port: 9011
spring:
  application:
    name: user
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: root
  cache:
    ehcache:
      config: classpath:ehcache/ehcache.xml
  rabbitmq:
      host: 220.249.111.162
      port: 16777
      username: admin
      password: adminrabbitmq123
        #确认消息已发送到交换机(Exchange)
      publisher-confirms: true
        #确认消息已发送到队列(Queue)
      publisher-returns: true
eureka:
   instance:
     prefer-ip-address: true
   client:
     service-url:
       defaultZone:  http://127.0.0.1:9200/eureka/


rocketmq:
  producer:
    groupName: ${spring.application.name}
    isOnOff: 'on'
    maxMessageSize: 4096
    namesrvAddr: 127.0.0.1:9876
    retryTimesWhenSendFailed: 2
    sendMsgTimeOut: 3000


