server:
  port: 9011
spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone:  http://127.0.0.1:9200/eureka/
