server:
  port: 9202
spring:
  application:
    name: oauth
  redis:
    host: localhost
    port: 6379
    jedis:
       pool:
         maxActive: 3
         maxIdle: 3
         minIdle: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password:


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone:  http://127.0.0.1:9200/eureka/

auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: changgou
  clientSecret: changgou
  cookieDomain: localhost
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/changgou.jks
    secret: changgou
    alias: changgou
    password: changgou